fix timeout script and use author version without broken tty redirect

diff --git a/files/usr/bin/timeout b/files/usr/bin/timeout
--- a/files/usr/bin/timeout
+++ b/files/usr/bin/timeout
@@ -1,30 +1,6 @@
 #!/bin/sh
-
+# http://www.pixelbeat.org/scripts/timeout
 # Execute a command with a timeout
-
-# Author:
-#	 http://www.pixelbeat.org/
-# Notes:
-#	 Note there is a timeout command packaged with coreutils since v7.0
-#	 If the timeout occurs the exit status is 124.
-#	 There is an asynchronous (and buggy) equivalent of this
-#	 script packaged with bash (under /usr/share/doc/ in my distro),
-#	 which I only noticed after writing this.
-#	 I noticed later again that there is a C equivalent of this packaged
-#	 with satan by Wietse Venema, and copied to forensics by Dan Farmer.
-# Changes:
-#	 V1.0, Nov	3 2006, Initial release
-#	 V1.1, Nov 20 2007, Brad Greenlee <brad@footle.org>
-#						Make more portable by using the 'CHLD'
-#						signal spec rather than 17.
-#	 V1.3, Oct 29 2009, Ján Sáreník <jasan@x31.com>
-#						Even though this runs under dash,ksh etc.
-#						it doesn't actually timeout. So enforce bash for now.
-#						Also change exit on timeout from 128 to 124
-#						to match coreutils.
-#	 V2.0, Oct 30 2009, Ján Sáreník <jasan@x31.com>
-#						Rewritten to cover compatibility with other
-#						Bourne shell implementations (pdksh, dash)
 
 if [ "$#" -lt "2" ]; then
 	echo "Usage:   $(basename "$0") timeout_in_seconds command" >&2
@@ -47,12 +23,12 @@ watchit()
 	kill -ALRM $$
 }
 
-watchit "$1" & a=$!		 #start the timeout
+watchit $1& a=$!		 #start the timeout
 shift					 #first param was timeout for sleep
 trap "cleanup" ALRM INT  #cleanup after timeout
-"$@" < /dev/tty & wait $!; RET=$?	 #start the job wait for it and save its return value
-kill -ALRM "$a"			 #send ALRM signal to watchit
-wait "$a"					 #wait for watchit to finish cleanup
+"$@"& wait $!; RET=$?	 #start the job wait for it and save its return value
+kill -ALRM $a			 #send ALRM signal to watchit
+wait $a					 #wait for watchit to finish cleanup
 exit $RET				 #return the value
 
 # vim: set filetype=sh ai noet ts=4 sw=4 sts=4 :
