use ash based registrator as default

diff --git a/files/usr/sbin/registrator b/files/usr/sbin/registrator
--- a/files/usr/sbin/registrator
+++ b/files/usr/sbin/registrator
@@ -1,209 +1,270 @@
-#!/usr/bin/lua
+#!/bin/sh
 
-require("luci.model.uci")
-require("luci.httpclient")
-require("luci.ip")
-require("luci.json")
-require("luci.sys")
-require("luci.util")
-require("nixio.fs")
+. /lib/functions.sh
+. /usr/share/libubox/jshn.sh
 
--- Init state session
-local ltn12 = require "luci.ltn12"
-local table = require "table"
-local uci = luci.model.uci.cursor_state()
+set -e
 
-function request_to_buffer(uri, options)
-	local source, code, msg = request_to_source(uri, options)
-	local output = {}
+printhelp() {
+        printf "registrator - maintains the knotennummer for routers\n
+see https://github.com/weimarnetz/registrator
 
-	if not source then
-		return nil, code, msg
-	end
-	
-	source = ltn12.pump.all(source, (ltn12.sink.table(output)))
-	
-	if not source then
-		return nil, code
-    end
+Usage: /usr/sbin/registrator <status|heartbeat|register>
 
-	local result = table.concat(output)
-	
-	return result, code 
-end
+"
+}
 
-function request_to_source(uri, options)
-	local status, response, buffer, sock = luci.httpclient.request_raw(uri, options)
-	if not status then
-		return status, response, buffer
-	elseif status ~= 200 and status ~= 201 and status ~= 303 and status ~= 206 then
-		return nil, status, buffer
-	end
-	if response.headers["Transfer-Encoding"] == "chunked" then
-        local chunksource = luci.httpclient.chunksource(sock, buffer)
-        return chunksource, status
-	else
-        local result = ltn12.source.cat(ltn12.source.string(buffer), sock:blocksource())
-        return result, status
-	end
-end
+# save positional argument, as it would get overwritten otherwise.
+CMD_1="$1"
+CMD_2="$2"
+if [ -z "$CMD_1" ] || ([ "$CMD_1" != "status" ] && [ "$CMD_1" != "heartbeat" ] && [ "$CMD_1" != "register" ]); then
+        [ "$CMD_1" != "-h" ] && [ "$CMD_1" != "--help" ] && printf "Unrecognized argument %s.\n\n" "$CMD_1"
+        printhelp
+        exit 1
+fi
 
-function sendHeartbeat(nodenumber)
-    local registratorserver = uci:get("ffwizard", "settings", "registrator") or "reg.weimarnetz.de"
-    local network = uci:get("ffwizard", "settings", "ipschema") or "ffweimar"
-    local uri = "http://"..registratorserver.."/"..network.."/knoten/"..nodenumber
+#################################
+#                               #
+# log messages to syslog        #
+#                               #
+#################################
+log_system() {
+  level="$1"
+  message="$2"
+        logger -s -t registrator -p "$1" "$message"
+}
 
-    return write_to_registrator("PUT", uri)
-end
-
-function registerNode()
-    local registratorserver = uci:get("ffwizard", "settings", "registrator") or "reg.weimarnetz.de"
-    local network = uci:get("ffwizard", "settings", "ipschema") or "ffweimar"
-    local uri = "http://"..registratorserver.."/"..network.."/knoten"
-
-    local result = write_to_registrator("POST", uri)
-    if result['success'] == true then
-        setNodeNumber(result['nodenumber'])
-    end
-    return result
-end
-
-function getStatus()
-    local registratorserver = uci:get("ffwizard", "settings", "registrator") or "reg.weimarnetz.de"
-    local network = uci:get("ffwizard", "settings", "ipschema") or "ffweimar"
-
-    local mac = getMac()
-    local params = {}
-    params['mac'] = mac
-
-    -- TODO: add https support, needs TLS context
-    local options = {
-        method = "GET",
-        params = params,
-    }
-    local uri = "http://"..registratorserver.."/"..network.."/knotenByMac"
-
-    local msg, code = request_to_buffer(uri, options)
-
-    local query_result = luci.json.decode(msg)
-
-    if code == 200 then
-        local nodenumber = query_result['result']['number']
-        nixio.syslog("info", mac.." found with number "..nodenumber)
-        return assemble_result(true, code, "Registrator: "..mac.." found with number ".. nodenumber, nodenumber)
-    elseif code then
-        nixio.syslog("warning", "could not find mac address "..mac)
-        return assemble_result(false, code,  "Registrator: could not find mac address "..mac, nil)
-    end
-end
-
-function write_to_registrator(method, uri)
-    local params = {}
-    params['mac'] = getMac()
-    params['pass'] = getPubkey()
-    -- TODO: add https support, needs TLS context
-    local options = {
-        method = method,
-        params = params,
-    }
-
-    local msg, code = request_to_buffer(uri, options)
-
-    local query_result = luci.json.decode(msg)
-
-    if code == 200 or code == 303 then
-        local nodenumber_from_result = query_result['result']['number']
-        nixio.syslog("info", "nodenumber "..nodenumber_from_result.." successfully updated")
-        return assemble_result(true, code, "Registrator: ".. nodenumber_from_result .." successfully updated", nodenumber_from_result)
-    elseif code == 201 then
-        local nodenumber_from_result = query_result['result']['number']
-        nixio.syslog("info", nodenumber_from_result.." successfully created")
-        return assemble_result(true, code, "Registrator: ".. nodenumber_from_result .." successfully created", nodenumber_from_result)
-    elseif code then
-        nixio.syslog("warning", "Failed to update/register node with mac "..params['mac'].." with code "..code)
-        return assemble_result(false, code, "Registrator: failed to update/egister node with mac "..params['mac'].." with code "..code, nil)
+#################################
+#                               #
+# Query status from registrator #
+#                               #
+#################################
+get_status() {
+  mac="$(get_mac)"
+  request_result=""
+  reg_status=""
+  request_result="$(send_http_request GET knotenByMac mac=$mac)"
+  if [ "$?" -eq 0 ]; then
+    json_load "$request_result"
+    json_get_var status status
+    json_select result
+    json_get_var nodenumber number
+    if [ "$status" -eq 200 ]; then
+      log_system "notice" "found mac $mac with number $nodenumber"
+      reg_status=$(build_result 1 "$status" "Registrator: found mac $mac with number $nodenumber" "$nodenumber")
+    elif [ -n "$status" ]; then
+      log_system "warn" "could not find mac $mac"
+      reg_status=$(build_result 0 "$status" "Registrator: could not find mac address $mac")
     else
-        nixio.syslog("warning", "Uupppsss: Something went wrong communicating with the registrator")
-        return assemble_result(false, code, "Uupppsss: Something went wrong communicating with the registrator", nil)
-    end
-end
+      log_system "err" "could not connect to the registrator service"
+      reg_status=$(build_result 0 500 "There's a problem connecting to the registrator server, please ask weimarnetz for help")
+    fi
+  else
+    log_system "err" "There's a problem receiving results from the server"
+    reg_status=$(build_result 0 500 "There's a problem receiving results from the server")
+  fi
+  echo "$reg_status"
+}
 
-function assemble_result(success, code, message, nodenumber)
-    local result = {}
-    result['success'] = success
-    result['code'] = code
-    result['message'] = message
-    if not nodenumber ~= nil then
-        result['nodenumber'] = nodenumber
-    end
-    return result
-end
+#################################
+#                               #
+# register new node             #
+#                               #
+#################################
+register_node() {
+  reg_status="$(write_to_registrator POST knoten)"
+  json_load "$reg_status"
+  json_get_var success success
+  json_get_var nodenumber nodenumber
+  if [ "$success" ]; then
+    store_nodenumber "$nodenumber"
+  fi
+  json_cleanup
+  echo "$reg_status"
+}
 
-function getMac()
-    local laninterface = uci:get("network", "lan", "ifname") or uci:get("network", "lan", "device")
-    local parameter = {}
-    parameter['name'] = laninterface
-    local devicestatus = luci.util.ubus("network.device", "status", parameter)
-    return devicestatus['macaddr']
-end
+#################################
+#                               #
+# send_heartbeat for node       #
+#                               #
+#################################
+send_heartbeat() {
+  nodenumber="$1"
+  echo "$(write_to_registrator PUT knoten/$nodenumber)"
+}
 
-function getPubkey()
-    -- we don't need a password anymore
-    return "pseudopassword"
-end
+#################################
+#                               #
+# stor new node number          #
+#                               #
+#################################
+store_nodenumber() {
+  nodenumber="$1"
+  uci_set ffwizard settings nodenumber $nodenumber
+  uci_commit
+  log_system "notice" "set new nodenumber to $nodenumber"
+}
 
-function getNodeNumber()
-    local nodenumber = tonumber(uci:get("ffwizard", "settings", "nodenumber")) or -1
-    if nodenumber == -1 then
-        nodenumber = tonumber(uci:get("meshwizard", "community", "nodenumber")) or -1
-        if nodenumber > 0 then
-            setNodeNumber(nodenumber)
-        end
-    end
-    return nodenumber
-end
+#################################
+#                               #
+# write to registrator          #
+#                               #
+#################################
+write_to_registrator() {
+  method="$1"
+  uri="$2"
 
-function setNodeNumber(nodenumber)
-    uci:set("ffwizard", "settings", "nodenumber", nodenumber)
-    uci:commit("ffwizard")
-    nixio.syslog("info", "set new nodenumber to "..nodenumber)
-end
-
-function printUsage()
-    print("Usage: "..arg[0].." <status|heartbeat|register>")
-    print("returns a json containing fields success, code (http status code from registrator), message (human readable error message) and optional a nodenumber")
-    os.exit()
-end
-
-nixio.openlog("registrator")
-nixio.syslog("debug", "registrator started")
-
-if #arg ~= 1 and #arg ~= 2 then
-    printUsage()
-end
-
-if arg[1] == "status" then
-    print(luci.json.encode(getStatus()))
-elseif arg[1] == "heartbeat" then
-    if arg[2] ~= nil and type(tonumber(arg[2])) == "number" then
-        print(luci.json.encode(sendHeartbeat(tonumber(arg[2]))))
+  mac="$(get_mac)"
+  request_result=""
+  reg_status=""
+  request_result="$(send_http_request $method $uri "mac=$mac&pass=pass")"
+  if [ "$?" -eq 0 ]; then
+    json_load "$request_result"
+    json_get_var status status
+    json_select result > /dev/null
+    json_get_var nodenumber number
+    if [ "$status" -eq 200 ] || [ "$status" -eq 303 ]; then
+      log_system "notice" "found mac $mac with number $nodenumber and/or successfully updated"
+      reg_status=$(build_result 1 "$status" "Registrator: $nodenumber found for mac $mac and/or successfully updated" "$nodenumber")
+    elif [ "$status" -eq 201 ]; then
+      log_system "notice" "nodenumber $nodenumber successfully created for mac $mac"
+      reg_status=$(build_result 1 "$status" "Registrator: nodenumber $nodenumber successfully created for mac address $mac")
+    elif [ -n "$status" ]; then
+      log_system "warn" "Failed to update/register node with mac $mac with code $status"
+      reg_status=$(build_result 0 "$status" "Registrator: Failed to update/register node with mac address $mac")
     else
-        local status = getStatus()
-        local nodenumber = getNodeNumber()
-        if status['success'] and status['nodenumber'] == nodenumber then
-            print(luci.json.encode(sendHeartbeat(nodenumber)))
-        elseif not status['success'] and nodenumber > 0 and nodenumber < 1001 then
-            print(luci.json.encode(sendHeartbeat(nodenumber)))
-        else
-            print(luci.json.encode(assemble_result(false, -3, "Could not send heartbeat! Node should be registered first, let's do it now!", nodenumber)))
-            print(luci.json.encode(registerNode()))
-        end
-    end
-elseif arg[1] == "register" then
-    print(luci.json.encode(registerNode()))
-else
-    printUsage()
-end
+      log_system "err" "could not connect to the registrator service"
+      reg_status=$(build_result 0 500 "There's a problem connecting to the registrator server, please ask weimarnetz for help")
+    fi
+  else
+    log_system "err" "There's a problem receiving results from the server"
+    reg_status=$(build_result 0 500 "There's a problem receiving results from the server")
+  fi
+  echo "$reg_status"
+}
 
-nixio.syslog("debug", "registrator finished")
-nixio.closelog()
+#################################
+#                               #
+# build result return object    #
+#                               #
+#################################
+build_result() {
+  success="$1"
+  code="$2"
+  message="$3"
+  nodenumber="$4"
+  json_init
+  json_add_boolean success $success
+  json_add_int code $code
+  json_add_string message "$message"
+  if [[ -n "$nodenumber" ]]; then
+    json_add_int nodenumber $nodenumber
+  fi
+  result="$(json_dump)"
+  echo "$result"
+}
+
+#################################
+#                               #
+# get mac address from lan      #
+#                               #
+#################################
+get_mac() {
+  local laninterface=$(uci_get network lan ifname)
+  if [ -z $laninterface ]; then
+    laninterface=$(uci_get network lan device)
+  fi
+  json_init
+  json_add_string name "$laninterface"
+  json_load  "$(ubus -v call network.device status "$(json_dump)")"
+  json_get_var macaddr macaddr
+  echo $macaddr
+}
+
+#################################
+#                               #
+# get nodenumber          #
+#                               #
+#################################
+get_nodenumber() {
+  nodenumber=$(uci_get ffwizard settings nodenumber -1)
+  if [ "$nodenumber" -eq -1 ]; then
+    nodenumber=$(uci_get meshwizard community nodenumber -1)
+    if [ "$nodenumber" -gt 0 ]; then
+      set_nodenumber "$nodenumber"
+    fi
+  fi
+  echo "$nodenumber"
+}
+
+#################################
+#                               #
+# set nodenumber          #
+#                               #
+#################################
+set_nodenumber() {
+  nodenumber="$1"
+  if [ -n "$nodenumber" ]; then
+    uci_set ffwizard settings nodenumber $nodenumber
+    uci_commit
+    log_system "notice" "set new nodenumber to $nodenumber"
+  fi
+}
+
+################################
+#                              #
+#   Send data to registrator   #
+#                              #
+################################
+send_http_request() {
+  TARGET="$(uci_get freifunk community registrator| sed -e 's/http\(s\)\{0,1\}:\/\///g')"
+  if [ -z $TARGET ]; then
+    TARGET="reg.weimarnetz.de"
+  fi
+  NETWORK="$(uci_get ffwizard settings ipschema)"
+  if [ -z $NETWORK ]; then
+    NETWORK="ffweimar"
+  fi
+  METHOD=$1
+  URI=$2
+  PARAMS=$3
+
+  MSG="\
+$METHOD /${NETWORK}/${URI}?${PARAMS} HTTP/1.0\r
+User-Agent: nc/0.0.1\r
+Host: $TARGET\r
+\r\n"
+  result=""  
+  result="$(printf "$MSG" | nc $TARGET 80|sed -e '1,/^\r$/d')"
+  xyz=$(jshn -r "$result")
+  exitcode=$?
+  if [ $exitcode -ne 0 ]; then
+    log_system "err" "Mist, I was not able to parse the result as valid json"
+    return 1
+  fi
+  echo "$result"
+}
+
+if [ "$CMD_1" == "status" ]; then
+  echo $(get_status)
+elif [ "$CMD_1" == "heartbeat" ]; then
+  if [ -n "$CMD_2" ] && [ "$CMD_2" -eq "$CMD_2" ]; then #checks if CMD_2 exists and is a number
+    echo $(send_heartbeat $CMD_2)
+  else
+    json_load "$(get_status)"
+    json_get_var success success
+    json_get_var nodenumber nodenumber
+    json_cleanup
+    stored_nodenumber="$(get_nodenumber)"
+    if [ "$success" ] && [ "$nodenumber" -eq "$stored_nodenumber" ]; then
+      echo $(send_heartbeat $nodenumber)
+    elif [ ! "$success" ] && [ "$stored_nodenumber" -gt 0 ] && [ "$stored_nodenumber" -lt 1001 ]; then
+      echo $(send_heartbeat $nodenumber)
+    else
+      log_system "err" "Could not send heartbeat! Node $nodenumber should be registered first, let's do it now!"
+      echo $(register_node)
+    fi
+  fi
+elif [ "$CMD_1" == "register" ]; then
+  echo $(register_node)
+fi
