verschlimmbesserung

diff --git a/files/etc/kalua/net b/files/etc/kalua/net
--- a/files/etc/kalua/net
+++ b/files/etc/kalua/net
@@ -1,5 +1,47 @@
 #!/bin/sh
 
+_net_dns2ip()
+{
+	local dns="$1"
+	local go
+
+	# explode $( nslookup host86-139-31-49.range86-139.btcentralplus.com )
+	# Server: 127.0.0.1 Address 1: 127.0.0.1 localhost Name: host86-139-31-49.range86-139.btcentralplus.com Address 1: 86.139.31.49 host86-139-31-49.range86-139.btcentralplus.com
+	explode $( nslookup "$dns" || echo 'ERROR ERROR' )
+
+	while shift; do {
+		case "$1" in
+			'ERROR'|'')
+				return 1
+			;;
+			'Name:')
+				go='true'
+			;;
+			'Address:'|'Address')
+				[ "$go" = 'true' ] || continue
+
+				# 'Address 1: 84.38.67.43'
+				# 'Address 1: 2a02:2e0:3fe:100::8 redirector.heise.de'
+				# 'Address 2: 193.99.144.80 redirector.heise.de'
+				# 'Address:    193.99.144.80'	// spaces on kernel 2.4
+				[ "$1" = 'Address' ] && shift
+				shift
+
+				case "$1" in
+					*':'*)
+						# ignore IPv6
+					;;
+					*)
+						echo "$1"
+						return 0
+					;;
+				esac
+			;;
+		esac
+	} done
+}
+
+
 _net_get_rxtx()
 {
 	local dev="$1"
@@ -35,14 +77,13 @@ _net_tcp_port_reachable()		# please call with 2>/dev/null otherwise you
 	# we can't rely on '-w3' or '-z' because of lobotomized busybox netcat
 	timeout 5 echo "foo" | nc "$server" "$port" 2>/dev/null >"$file" || touch "$file.error" 
 	if [ -n "$check_output" ]; then
-		local success=0
-		grep -sq -- "$check_output" "$file" && success=1 
-		[ "$success" ] && break
-		_log it $funcname daemon info "[ERR] '$( cat "$file" )'"
+		if ! grep -sq -- "$check_output" "$file"; then
+			rc=1
+			_log it $funcname daemon info "[ERR] '$( cat "$file" )'"
+		fi	
 	else
 		[ -e "$file.error" ] && {
 				rc=1
-				break
 		}
 	fi
 	rm "$file" "$file.error" 2>/dev/null
diff --git a/files/etc/kalua/vpn b/files/etc/kalua/vpn
--- a/files/etc/kalua/vpn
+++ b/files/etc/kalua/vpn
@@ -1,15 +1,16 @@
 #!/bin/sh
+# shellcheck disable=SC2039
 
 _vpn_needed()
 {
 	[ -z "$INETOFFER" ] && INETOFFER="$( _net local_inet_offer )"
 
-	[ "$INETOFFER" = "false" -a -z "$( uci -q get system.vpn.force )" ] && {
+	[ "$INETOFFER" = "false" ] && {
 		_log it $FUNC daemon debug "no local default gateway - abort"
 		return 1
 	}
 
-	[ "$( uci -q get system.vpn.enable )" = "off" ] && {
+	[ "$( uci -q get meshnode.vpn.disabled )" -eq "1" ] && {
 		_log it $FUNC daemon debug "vpn disabled by config - abort"
 		return 1
 	}
@@ -127,7 +128,7 @@ _vpn_write_vtun_conf()
 		local kalua_roaming_net="100.64.0.0/10"
 	local mytable="weimarnetz_anonym"
 	local anonym
-		local VPN_SERVER_IP="$(_net dns2ip $VPN_SERVER)"
+	local VPN_SERVER_IP="$(_net dns2ip $VPN_SERVER)"
 
 	[ "$( uci -q get system.vpn.enable )" = "innercity" ] && {
 		anonym="# (inactiv):"
@@ -209,7 +210,7 @@ _vpn_remove_vtun_conf ()
 _vpn_defer_start ()
 {
 	DIRTY=
-	[ "$( uci -q get meshnode.vpn.disabled )" = "1" ]	&& DIRTY="VPN disabled"
+	[ "$( uci -q get meshnode.vpn.disabled )" = "1" ] && DIRTY="VPN disabled"
 	[ -e "/tmp/LOWMEM" ]				&& DIRTY="lowmem"
 	[ -n "$FAILSAFE" ]				&& DIRTY="failsafe"
 	[ -n "$READONLY" ]				&& DIRTY="readonly"
@@ -240,70 +241,70 @@ _vpn_probe_vtund_type ()
 
 _vpn_build_vars()
 {
-  local FUNC="vpn_build_vars"
+	local FUNC="vpn_build_vars"
 
-  . /usr/share/libubox/jshn.sh		# OpenWrt JSON-helpers
+	. /usr/share/libubox/jshn.sh		# OpenWrt JSON-helpers
 
-  DOMAIN="$( uci -q get system.vpn.domain )"	# e.g. 'weimarnetz.de'
-  PREFIX="$( uci -q get system.vpn.prefix )"	# e.g. 'vpn'
-  JSONPATH="$( uci -q get system.vpn.jsonpath )"	# e.g. '/freifunk/vpn/'
-  VTUNDTYPE="$( _vpn probe_vtund_type )"		# e.g. 'nossl_nolzo'
-  local TABLE=
+	DOMAIN="$( uci -q get system.vpn.domain )"	# e.g. 'weimarnetz.de'
+	PREFIX="$( uci -q get system.vpn.prefix )"	# e.g. 'vpn'
+	JSONPATH="$( uci -q get system.vpn.jsonpath )"	# e.g. '/freifunk/vpn/'
+	VTUNDTYPE="$( _vpn probe_vtund_type )"		# e.g. 'nossl_nolzo'
+	local TABLE=
 
-  for i in 1 2 3 4 5 6 7 8 9 10; do
-	HOST="${i}.${PREFIX}.${DOMAIN}"
-	URL="http://${HOST}${JSONPATH}"
+	for i in 1 2 3 4 5 6 7 8 9 10; do
+		HOST="${i}.${PREFIX}.${DOMAIN}"
+		URL="http://${HOST}${JSONPATH}"
 
-	if ! JSON=$( _curl it "${URL}" 2>/dev/null ); then
-	  _log it ${FUNC} daemon err "error fetching ${URL}"
-	else
-	   json_cleanup	# json_get_var variables are not cleaned otherwise.
-	   json_load "${JSON}" 2>/dev/null
-	   SERVER=	   json_get_var SERVER server
-	   CLIENTS=-1  json_get_var CLIENTS clients
-	   MTU=-1	   json_get_var MTU maxmtu
-	   PORT=-1	   json_get_var PORT port_vtun_${VTUNDTYPE}
+		if ! JSON=$( _curl it "${URL}" 2>/dev/null ); then
+			_log it ${FUNC} daemon err "error fetching ${URL}"
+		else
+			json_cleanup	# json_get_var variables are not cleaned otherwise.
+			json_load "${JSON}" 2>/dev/null
+			SERVER=	   json_get_var SERVER server
+			CLIENTS=-1 json_get_var CLIENTS clients
+			MTU=-1	   json_get_var MTU maxmtu
+			PORT=-1	   json_get_var PORT port_vtun_${VTUNDTYPE}
 
-	   PING="$( _net ping_getlatency "${SERVER}" )";
-	   _net tcp_port_reachable "$SERVER" "$PORT" || PORT=-1
+			_net tcp_port_reachable "$SERVER" "$PORT" || PORT=-1
 
-	vars_are_sane()
-	{
-		test -n "$SERVER" -a "$CLIENTS" -ge 0 -a "$MTU" -ge 0 -a "$PORT" -ge 0 2>/dev/null
-	}
+			vars_are_sane()
+			{
+				test -n "$SERVER" -a "$CLIENTS" -ge 0 -a "$MTU" -ge 0 -a "$PORT" -ge 0 2>/dev/null
+			}
 
-	   if vars_are_sane; then
-			 _log it ${FUNC} daemon notice "got ${SERVER} - ping: ${PING}ms"
-		 # here we build a long string:
-		 # each valid varset is a small mini-shell-script (eval-able)
-		 # and (with a space) appended to the next one. later we choose only 1 entry.
-		 TABLE="${TABLE}PING=$PING;NUMBER=$i;CLIENTS=$CLIENTS;MTU=$MTU;PORT=$PORT;SERVER=$SERVER "
-	   else
-			_log it ${FUNC} daemon err "error: invalid data on ${URL}"
-	   fi
-	fi
-  done
+			if vars_are_sane; then
+				_log it ${FUNC} daemon notice "got ${SERVER}"
 
-# no vpn, then exit early
-[ -z "$TABLE" ] && return 1
+				# here we build a long string:
+				# each valid varset is a small mini-shell-script (eval-able)
+				# and (with a space) appended to the next one. later we choose only 1 entry.
+				TABLE="${TABLE}PING=$PING;NUMBER=$i;CLIENTS=$CLIENTS;MTU=$MTU;PORT=$PORT;SERVER=$SERVER "
+			else
+				_log it ${FUNC} daemon err "error: invalid data on ${URL}"
+			fi
+		fi
+	done
 
-# get a random VPN entry
-eval $( _list random_element "$TABLE" )
+	# no vpn, then exit early
+	[ -z "$TABLE" ] && return 1
+
+	# get a random VPN entry
+	eval $( _list random_element "$TABLE" )
 
 
- VPN_SERVER="${SERVER}"
+	VPN_SERVER="${SERVER}"
 
- _log it ${FUNC} daemon notice "using ${VPN_SERVER} - ping: ${PING}ms  clients: ${CLIENTS}	port: ${PORT}  mtu: ${MTU}"
- NODE_NUMBER="$( uci -q get system.profile.nodenumber )"
- HOSTNAME="$( uci -q get system.@system[0].hostname )"
- [ -z "${HOSTNAME}" ] && HOSTNAME="node${NODE_NUMBER}"
- SERV="${VPN_SERVER}"	# _ip4|_ip6 fallback?
- CONF="/var/etc/olsrd.conf"			# old_style
- KNOT="${NODE_NUMBER}"
- VTUN="/tmp/vtund.conf"
+	_log it ${FUNC} daemon notice "using ${VPN_SERVER} - ping: ${PING}ms  clients: ${CLIENTS}	port: ${PORT}  mtu: ${MTU}"
+	NODE_NUMBER="$( uci -q get system.profile.nodenumber )"
+	HOSTNAME="$( uci -q get system.@system[0].hostname )"
+	[ -z "${HOSTNAME}" ] && HOSTNAME="node${NODE_NUMBER}"
+	SERV="${VPN_SERVER}"	# _ip4|_ip6 fallback?
+	CONF="/var/etc/olsrd.conf"			# old_style
+	KNOT="${NODE_NUMBER}"
+	VTUN="/tmp/vtund.conf"
 
- [ "${1}" != "stop" ] && INETOFFER="$( _net local_inet_offer )"
+	[ "${1}" != "stop" ] && INETOFFER="$( _net local_inet_offer )"
 	
- eval "$( _ipsystem get )"
+	eval "$( _ipsystem get )"
 }
 # vim: set filetype=sh ai noet ts=4 sw=4 sts=4 :
