add vim modeline and retab all the files for better tab/spaces consistency

diff --git a/files/etc/kalua/vpn b/files/etc/kalua/vpn
--- a/files/etc/kalua/vpn
+++ b/files/etc/kalua/vpn
@@ -24,7 +24,7 @@ _vpn_start ()
 	_watch vpn && { # FIXME! Workaround until lock -n <filename> is implemented
 		_log it $FUNC daemon info 'already running, aborting'
 		return 1
-        }
+		}
 
 	lock -n $LOCKFILE
 
@@ -124,10 +124,10 @@ _vpn_write_vtun_conf()
 	local LINE=""
 	local STATIC_ROUTE="$( _vpn_get_static_route )"
 	local particpant_net="10.63.0.0/16"			# fixme! hardcoded
-        local kalua_roaming_net="100.64.0.0/10"
+		local kalua_roaming_net="100.64.0.0/10"
 	local mytable="weimarnetz_anonym"
 	local anonym
-        local VPN_SERVER_IP="$(_net dns2ip $VPN_SERVER)"
+		local VPN_SERVER_IP="$(_net dns2ip $VPN_SERVER)"
 
 	[ "$( uci -q get system.vpn.enable )" = "innercity" ] && {
 		anonym="# (inactiv):"
@@ -151,11 +151,11 @@ Node$KNOT {
 
 		program "grep -q $mytable /etc/iproute2/rt_tables || echo 50 $mytable >>/etc/iproute2/rt_tables" wait;
 		program "$anonym ip rule add from $particpant_net prio 30010 table $mytable" wait;
-                program "$anonym ip rule add from $kalua_roaming_net prio 30020 table $mytable" wait;
+				program "$anonym ip rule add from $kalua_roaming_net prio 30020 table $mytable" wait;
 
 		# dont send packets to private networks over vpn
 		program "$anonym ip rule add to 169.254.0.0/24 prio 30005 lookup main" wait;
-		program "$anonym ip rule add to 10.0.0.0/8     prio 30004 lookup main" wait;
+		program "$anonym ip rule add to 10.0.0.0/8	   prio 30004 lookup main" wait;
 		program	"$anonym ip rule add to 100.64.0.0/10  prio 30001 lookup main" wait;
 		program "$anonym ip rule add to 192.168.0.0/16 prio 30003 lookup main" wait;
 		program "$anonym ip rule add to 172.16.0.0/12  prio 30002 lookup main" wait;
@@ -178,11 +178,11 @@ Node$KNOT {
 		program "$anonym ip rule del to 100.64.0.0/10  prio 30001 lookup main" wait;
 		program "$anonym ip rule del to 172.16.0.0/12  prio 30002 lookup main" wait;
 		program "$anonym ip rule del to 192.168.0.0/16 prio 30003 lookup main" wait;
-		program "$anonym ip rule del to 10.0.0.0/8     prio 30004 lookup main" wait;
+		program "$anonym ip rule del to 10.0.0.0/8	   prio 30004 lookup main" wait;
 		program "$anonym ip rule del to 169.254.0.0/24 prio 30005 lookup main" wait;
 
 		program "$anonym ip rule del from $kalua_roaming_net prio 30020 table $mytable" wait; 
-                program "$anonym ip rule del from $particpant_net prio 30010 table $mytable" wait;                    
+				program "$anonym ip rule del from $particpant_net prio 30010 table $mytable" wait;					  
 
 		program "ip route del $VPN_SERVER_IP via $STATIC_ROUTE" wait;
 		program "ip link set dev %% down" wait;
@@ -219,7 +219,7 @@ _vpn_defer_start ()
 		_log it init daemon debug "call: '$1' - abort: '$DIRTY'"
 		return 0
 	}
-  	return 1
+	return 1
 }
 
 _vpn_probe_vtund_type ()
@@ -252,37 +252,37 @@ _vpn_build_vars()
   local TABLE=
 
   for i in 1 2 3 4 5 6 7 8 9 10; do
-    HOST="${i}.${PREFIX}.${DOMAIN}"
-    URL="http://${HOST}${JSONPATH}"
+	HOST="${i}.${PREFIX}.${DOMAIN}"
+	URL="http://${HOST}${JSONPATH}"
 
-    if ! JSON=$( _curl it "${URL}" 2>/dev/null ); then
-      _log it ${FUNC} daemon err "error fetching ${URL}"
-    else
-       json_cleanup	# json_get_var variables are not cleaned otherwise.
-       json_load "${JSON}" 2>/dev/null
-       SERVER=     json_get_var SERVER server
-       CLIENTS=-1  json_get_var CLIENTS clients
-       MTU=-1      json_get_var MTU maxmtu
-       PORT=-1     json_get_var PORT port_vtun_${VTUNDTYPE}
+	if ! JSON=$( _curl it "${URL}" 2>/dev/null ); then
+	  _log it ${FUNC} daemon err "error fetching ${URL}"
+	else
+	   json_cleanup	# json_get_var variables are not cleaned otherwise.
+	   json_load "${JSON}" 2>/dev/null
+	   SERVER=	   json_get_var SERVER server
+	   CLIENTS=-1  json_get_var CLIENTS clients
+	   MTU=-1	   json_get_var MTU maxmtu
+	   PORT=-1	   json_get_var PORT port_vtun_${VTUNDTYPE}
 
-       PING="$( _net ping_getlatency "${SERVER}" )";
-       _net tcp_port_reachable "$SERVER" "$PORT" || PORT=-1
+	   PING="$( _net ping_getlatency "${SERVER}" )";
+	   _net tcp_port_reachable "$SERVER" "$PORT" || PORT=-1
 
 	vars_are_sane()
 	{
 		test -n "$SERVER" -a "$CLIENTS" -ge 0 -a "$MTU" -ge 0 -a "$PORT" -ge 0 2>/dev/null
 	}
 
-       if vars_are_sane; then
-             _log it ${FUNC} daemon notice "got ${SERVER} - ping: ${PING}ms"
-	     # here we build a long string:
-	     # each valid varset is a small mini-shell-script (eval-able)
-	     # and (with a space) appended to the next one. later we choose only 1 entry.
-	     TABLE="${TABLE}PING=$PING;NUMBER=$i;CLIENTS=$CLIENTS;MTU=$MTU;PORT=$PORT;SERVER=$SERVER "
-       else
-            _log it ${FUNC} daemon err "error: invalid data on ${URL}"
-       fi
-    fi
+	   if vars_are_sane; then
+			 _log it ${FUNC} daemon notice "got ${SERVER} - ping: ${PING}ms"
+		 # here we build a long string:
+		 # each valid varset is a small mini-shell-script (eval-able)
+		 # and (with a space) appended to the next one. later we choose only 1 entry.
+		 TABLE="${TABLE}PING=$PING;NUMBER=$i;CLIENTS=$CLIENTS;MTU=$MTU;PORT=$PORT;SERVER=$SERVER "
+	   else
+			_log it ${FUNC} daemon err "error: invalid data on ${URL}"
+	   fi
+	fi
   done
 
 # no vpn, then exit early
@@ -294,7 +294,7 @@ eval $( _list random_element "$TABLE" )
 
  VPN_SERVER="${SERVER}"
 
- _log it ${FUNC} daemon notice "using ${VPN_SERVER} - ping: ${PING}ms  clients: ${CLIENTS}  port: ${PORT}  mtu: ${MTU}"
+ _log it ${FUNC} daemon notice "using ${VPN_SERVER} - ping: ${PING}ms  clients: ${CLIENTS}	port: ${PORT}  mtu: ${MTU}"
  NODE_NUMBER="$( uci -q get system.profile.nodenumber )"
  HOSTNAME="$( uci -q get system.@system[0].hostname )"
  [ -z "${HOSTNAME}" ] && HOSTNAME="node${NODE_NUMBER}"
@@ -307,3 +307,4 @@ eval $( _list random_element "$TABLE" )
 	
  eval "$( _ipsystem get )"
 }
+# vim: set filetype=sh ai noet ts=4 sw=4 sts=4 :
